name: Build Dev Project

on:
    push:
        branches: ["dev"]
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
    group: "build"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 'dev' Branch
              uses: actions/checkout@v3
              with:
                  ref: dev
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18.18.0"
                  cache: npm
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npx next lint
            - name: Build
              run: npx next build
            - name: Static HTML Export
              run: npx next export
