name: Lint, Test, Build, and Deploy to dev

on:
    push:
        branches-ignore: ['main']
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
    group: 'build'
    cancel-in-progress: false

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node ${{ vars.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: npm
            - name: Install Dependencies
              run: npm ci
            - name: Run Linter
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node ${{ vars.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: npm
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test

    build:
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node ${{ vars.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
